# Generated by Django 4.2.5 on 2023-12-11 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="name",
            field=models.CharField(
                default=datetime.date.today(), max_length=30, verbose_name="item_name"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dancegroup",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="group",
                to="main.client",
                verbose_name="members",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateField(verbose_name="start_date"),
        ),
    ]
