# Generated by Django 4.2.5 on 2024-01-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_item_name_alter_dancegroup_members_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="records",
        ),
        migrations.RemoveField(
            model_name="dancegroup",
            name="members",
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.client",
                        verbose_name="client",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.dancegroup",
                        verbose_name="group",
                    ),
                ),
            ],
            options={
                "verbose_name": "group_member",
                "verbose_name_plural": "group_members",
            },
        ),
        migrations.CreateModel(
            name="ClientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.client",
                        verbose_name="client",
                    ),
                ),
                (
                    "test_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.testclass",
                        verbose_name="test_class",
                    ),
                ),
            ],
            options={
                "verbose_name": "client_record",
                "verbose_name_plural": "client_records",
            },
        ),
    ]
